<?php

namespace ContainerDx4eI7t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MhYHKkiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MhYHKki' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MhYHKki'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comment' => ['privates', '.errored..service_locator.MhYHKki.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator.MhYHKki": it needs an instance of "App\\Entity\\Comment" but this type has been excluded in "config/services.yaml".'],
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'comment' => 'App\\Entity\\Comment',
            'entityManagerInterface' => '?',
        ]);
    }
}
