<?php

namespace ContainerDx4eI7t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInteractiveLoginEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZdHc.KM.Symfony\Component\Security\Http\Event\InteractiveLoginEvent' shared service.
     *
     * @return \Symfony\Component\Security\Http\Event\InteractiveLoginEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ZdHc.KM": it references class "Symfony\\Component\\Security\\Http\\Event\\InteractiveLoginEvent" but no such service exists.');
    }
}
