<?php

namespace ContainerDx4eI7t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogoutSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\EventListener\LogoutSubscriber' shared autowired service.
     *
     * @return \App\EventListener\LogoutSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/EventListener/LogoutSubscriber.php';

        $container->services['App\\EventListener\\LogoutSubscriber'] = $instance = new \App\EventListener\LogoutSubscriber(($container->services['router'] ?? $container->getRouterService()));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\EventListener\\LogoutSubscriber', $container));

        return $instance;
    }
}
