<?php

namespace ContainerAeoiD8R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rbu7CBfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rbu7CBf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rbu7CBf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CommentController::deleteComment' => ['privates', '.service_locator.MhYHKki', 'get_ServiceLocator_MhYHKkiService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.12XOZIl', 'get_ServiceLocator_12XOZIlService', true],
            'App\\Controller\\HomeController::loadMoreTricks' => ['privates', '.service_locator.12XOZIl', 'get_ServiceLocator_12XOZIlService', true],
            'App\\Controller\\ProfileController::getProfile' => ['privates', '.service_locator.fNvIwJr', 'get_ServiceLocator_FNvIwJrService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.EE0.cm9', 'get_ServiceLocator_EE0_Cm9Service', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.Z9ydiC1', 'get_ServiceLocator_Z9ydiC1Service', true],
            'App\\Controller\\SigninController::signin' => ['privates', '.service_locator.s9WD7FO', 'get_ServiceLocator_S9WD7FOService', true],
            'App\\Controller\\SignupController::signup' => ['privates', '.service_locator.OF7Jmdt', 'get_ServiceLocator_OF7JmdtService', true],
            'App\\Controller\\SignupController::verifyUserEmail' => ['privates', '.service_locator.Yez7eur', 'get_ServiceLocator_Yez7eurService', true],
            'App\\Controller\\TrickController::category' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\TrickController::delete' => ['privates', '.service_locator.sqP2VXt', 'get_ServiceLocator_SqP2VXtService', true],
            'App\\Controller\\TrickController::deleteMedia' => ['privates', '.service_locator.sqP2VXt', 'get_ServiceLocator_SqP2VXtService', true],
            'App\\Controller\\TrickController::edit' => ['privates', '.service_locator.uW_PT3G', 'get_ServiceLocator_UWPT3GService', true],
            'App\\Controller\\TrickController::index' => ['privates', '.service_locator.sqP2VXt', 'get_ServiceLocator_SqP2VXtService', true],
            'App\\Controller\\TrickController::new' => ['privates', '.service_locator.uJI3b0P', 'get_ServiceLocator_UJI3b0PService', true],
            'App\\EventListener\\LoginSubscriber::onLogin' => ['privates', '.service_locator.ZdHc.KM', 'get_ServiceLocator_ZdHc_KMService', true],
            'App\\EventListener\\LogoutSubscriber::onLogout' => ['privates', '.service_locator.wrGrPsA', 'get_ServiceLocator_WrGrPsAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CommentController:deleteComment' => ['privates', '.service_locator.MhYHKki', 'get_ServiceLocator_MhYHKkiService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.12XOZIl', 'get_ServiceLocator_12XOZIlService', true],
            'App\\Controller\\HomeController:loadMoreTricks' => ['privates', '.service_locator.12XOZIl', 'get_ServiceLocator_12XOZIlService', true],
            'App\\Controller\\ProfileController:getProfile' => ['privates', '.service_locator.fNvIwJr', 'get_ServiceLocator_FNvIwJrService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.EE0.cm9', 'get_ServiceLocator_EE0_Cm9Service', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.Z9ydiC1', 'get_ServiceLocator_Z9ydiC1Service', true],
            'App\\Controller\\SigninController:signin' => ['privates', '.service_locator.s9WD7FO', 'get_ServiceLocator_S9WD7FOService', true],
            'App\\Controller\\SignupController:signup' => ['privates', '.service_locator.OF7Jmdt', 'get_ServiceLocator_OF7JmdtService', true],
            'App\\Controller\\SignupController:verifyUserEmail' => ['privates', '.service_locator.Yez7eur', 'get_ServiceLocator_Yez7eurService', true],
            'App\\Controller\\TrickController:category' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\TrickController:delete' => ['privates', '.service_locator.sqP2VXt', 'get_ServiceLocator_SqP2VXtService', true],
            'App\\Controller\\TrickController:deleteMedia' => ['privates', '.service_locator.sqP2VXt', 'get_ServiceLocator_SqP2VXtService', true],
            'App\\Controller\\TrickController:edit' => ['privates', '.service_locator.uW_PT3G', 'get_ServiceLocator_UWPT3GService', true],
            'App\\Controller\\TrickController:index' => ['privates', '.service_locator.sqP2VXt', 'get_ServiceLocator_SqP2VXtService', true],
            'App\\Controller\\TrickController:new' => ['privates', '.service_locator.uJI3b0P', 'get_ServiceLocator_UJI3b0PService', true],
            'App\\EventListener\\LoginSubscriber:onLogin' => ['privates', '.service_locator.ZdHc.KM', 'get_ServiceLocator_ZdHc_KMService', true],
            'App\\EventListener\\LogoutSubscriber:onLogout' => ['privates', '.service_locator.wrGrPsA', 'get_ServiceLocator_WrGrPsAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CommentController::deleteComment' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\HomeController::loadMoreTricks' => '?',
            'App\\Controller\\ProfileController::getProfile' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SigninController::signin' => '?',
            'App\\Controller\\SignupController::signup' => '?',
            'App\\Controller\\SignupController::verifyUserEmail' => '?',
            'App\\Controller\\TrickController::category' => '?',
            'App\\Controller\\TrickController::delete' => '?',
            'App\\Controller\\TrickController::deleteMedia' => '?',
            'App\\Controller\\TrickController::edit' => '?',
            'App\\Controller\\TrickController::index' => '?',
            'App\\Controller\\TrickController::new' => '?',
            'App\\EventListener\\LoginSubscriber::onLogin' => '?',
            'App\\EventListener\\LogoutSubscriber::onLogout' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CommentController:deleteComment' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\HomeController:loadMoreTricks' => '?',
            'App\\Controller\\ProfileController:getProfile' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SigninController:signin' => '?',
            'App\\Controller\\SignupController:signup' => '?',
            'App\\Controller\\SignupController:verifyUserEmail' => '?',
            'App\\Controller\\TrickController:category' => '?',
            'App\\Controller\\TrickController:delete' => '?',
            'App\\Controller\\TrickController:deleteMedia' => '?',
            'App\\Controller\\TrickController:edit' => '?',
            'App\\Controller\\TrickController:index' => '?',
            'App\\Controller\\TrickController:new' => '?',
            'App\\EventListener\\LoginSubscriber:onLogin' => '?',
            'App\\EventListener\\LogoutSubscriber:onLogout' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
