<?php

namespace ContainerAeoiD8R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SqP2VXtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sqP2VXt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sqP2VXt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'trick' => ['privates', '.errored..service_locator.sqP2VXt.App\\Entity\\Trick', NULL, 'Cannot autowire service ".service_locator.sqP2VXt": it needs an instance of "App\\Entity\\Trick" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManagerInterface' => '?',
            'trick' => 'App\\Entity\\Trick',
        ]);
    }
}
