<?php

namespace ContainerAeoiD8R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrick2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uW_PT3G.App\Entity\Trick' shared service.
     *
     * @return \App\Entity\Trick
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.uW_PT3G": it needs an instance of "App\\Entity\\Trick" but this type has been excluded in "config/services.yaml".');
    }
}
