<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDx4eI7t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDx4eI7t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDx4eI7t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDx4eI7t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDx4eI7t\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dx4eI7t',
    'container.build_id' => 'c41895ca',
    'container.build_time' => 1696800074,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDx4eI7t');
