<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMnLLS1i\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMnLLS1i/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMnLLS1i.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMnLLS1i\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMnLLS1i\App_KernelDevDebugContainer([
    'container.build_hash' => 'MnLLS1i',
    'container.build_id' => '97122ce9',
    'container.build_time' => 1699967677,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMnLLS1i');
